### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by xiaoxia7806** [RayanWang/Speech_emotion_recognition_BLSTM#21]
### Hi! Rayan! I'm sorry to disturb you, I have a issue :

**python find_best_model.py -d "berlin" -p E:\TensorFlow\Emo-DB\wav -l -e -c 7**
Using TensorFlow backend.
Writing berlin data set to file...
Traceback (most recent call last):
  File "find_best_model.py", line 167, in <module>
    extract_dataset(ds.data, nb_samples=len(ds.targets), dataset=dataset)
  File "E:\TensorFlow\GitHub\Speech_emotion_recognition_BLSTM-master\utility\audio.py", line 75, in extract_dataset
    hr_pitch = ShortTermFeatures.speed_feature(x, Fs, globalvars.frame_size * Fs, globalvars.step * Fs)
  File "C:\Users\asus\Anaconda3\envs\tensorflow\lib\site-packages\pyAudioAnalysis\ShortTermFeatures.py", line 485, in speed_feature
    x = signal[cur_p:cur_p + window]
 **TypeError: slice indices must be integers or None or have an __index__ method**

please help me about that! Thanks very much!

**Comment by fathimad11** [comment]
how you correct this
