### ISSUE TITLE
Speech_emotion_recognition_BLSTM error

### ISSUE THREAD

**Issue by thaingiW** [RayanWang/Speech_emotion_recognition_BLSTM#3]
Loading data and features...
Number of samples: 535
Traceback (most recent call last):
  File "/home/lwin/speech-emotion/Speech_emotion_recognition_BLSTM-master1/find_best_model.py", line 171, in <module>
    trials=trials)
  File "/usr/local/lib/python3.5/dist-packages/hyperas/optim.py", line 67, in minimize
    verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/hyperas/optim.py", line 115, in base_minimizer
    space=get_space(),
  File "./temp_model.py", line 203, in get_space
NameError: name 'sgd' is not defined
Please help to solve!

**Comment by RayanWang** [comment]
Hi, this is a bug and please modify this line of code:
    choice_val = {{choice(['adam', 'rmsprop', sgd])}} -> choice_val = {{choice(['adam', 'rmsprop', 'sgd'])}}
and it will work.

**Comment by thaingiW** [comment]
Thank you very much!!
